[project]
name = "symfun"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "xiangkeshen", email = "xks@example.com" }
]
requires-python = ">=3.13"
dependencies = ["sympy", "typing_extensions>=4.12.2"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/symfun"]